spring:
  mail:
    host: smtp.163.com
    username: 13526880238@163.com
    #   该密码是开启pop3/smtp服务时的临时密码,而不是我们使用该账号登录时的密码
    password: RPTFNPLKHETGFTVC
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true