#security:
#  basic:
#    enabled: false

server:
  port: 8081

  servlet:
    session:
      timeout: 60
#spring:
#  application:
#    name: security
#  boot:
#    admin:
#      client:
#        url: http://localhost:8080

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
security:
  oauth2:
    client:
      client-id: test
      client-secret: test1234
      registered-redirect-uri: http://mrbird.cc


spring:
  redis:
    cluster:
      nodes:
        - 106.54.206.104:8001
        - 106.54.206.104:8002
        - 106.54.206.104:8003
        - 106.54.206.104:8004
        - 106.54.206.104:8005
        - 106.54.206.104:8006
      max-redirects: 6
    lettuce:
      shutdown-timeout: 5000ms
      pool:
        max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
