
#security:
#  basic:
#    enabled: false

server:
  port: 8081

  servlet:
    session:
      timeout: 60
#spring:
#  application:
#    name: security
#  boot:
#    admin:
#      client:
#        url: http://localhost:8080

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

