spring:
  application:
    name: validtorDemo

server:
  port: 9090
  servlet:
    #context-path指定后在nginx反向代理中有点作用
    context-path: /demo

#junjie:
#  test: ${TESTNAME} #TESTNAME 该变量值配置在系统环境变量中，启动时会自动从系统环境中获取，如果没有配置则获取不到